---
  - name: Check if erp App exists
    stat: path="{{ bench_path }}/apps/erp"
    register: app

  - name: Get the erp app
    command: bench get-app erp {{ erp_repo_url }} --branch {{ erp_branch }}
    args:
      creates: "{{ bench_path }}/apps/erp"
      chdir: "{{ bench_path }}"
    when: not app.stat.exists and not without_erp

  - name: Check whether the site already exists
    stat: path="{{ bench_path }}/sites/{{ site }}"
    register: site_folder
    when: not without_site

  - name: Create a new site
    command: "bench new-site {{ site }} --admin-password '{{ admin_password }}' --mariadb-root-password '{{ mysql_root_password }}'"
    args:
      chdir: "{{ bench_path }}"
    when: not without_site and not site_folder.stat.exists

  - name: Install erp to default site
    command: "bench --site {{ site }} install-app erp"
    args:
      chdir: "{{ bench_path }}"
    when: not without_site and not without_erp
...